### ISSUE TITLE
Zig template doesn't build

### ISSUE THREAD

**Issue by squeaktoy** [aduros/wasm4#685]
after doing `w4 new --zig test` and trying `zig build -Doptimize=ReleaseSmall` I get this:
```
/home/user/my_software/test4/build.zig:8:14: error: no field named 'cpu_arch' in struct 'Build.ResolvedTarget'
            .cpu_arch = .wasm32,
             ^~~~~~~~
/usr/lib64/zig/9999/lib/std/Build.zig:2242:28: note: struct declared here
pub const ResolvedTarget = struct {
                           ^~~~~~
referenced by:
    runBuild__anon_8077: /usr/lib64/zig/9999/lib/std/Build.zig:1851:37
    steps__anon_7900: /usr/lib64/zig/9999/lib/build_runner.zig:1033:29
    remaining reference traces hidden; use '-freference-trace' to see all reference traces
```

And even with Zig 0.11.0 it fails:
```
/home/user/my_software/test4/build.zig:14:9: error: no field named 'entry' in struct 'Build.Step.Compile'
    exe.entry = .disabled;
        ^~~~~
/usr/lib64/zig/0.11.0/lib/std/Build/Step/Compile.zig:1:1: note: struct declared here
const builtin = @import("builtin");
^~~~~
referenced by:
    runBuild__anon_7138: /usr/lib64/zig/0.11.0/lib/std/Build.zig:1639:37
    remaining reference traces hidden; use '-freference-trace' to see all reference traces
```

Removing the `exe.entry = .disabled;` line makes matters even worse:
```
zig build-exe cart ReleaseSmall wasm32-freestanding: error: the following command failed with 1 compilation errors:
/usr/lib64/zig/0.11.0/bin/zig build-exe --stack 14752 /home/user/my_software/test4/src/main.zig -OReleaseSmall --cache-dir /home/user/my_software/test4/zig-cache --global-cache-dir /home/user/.cache/zig --name cart --import-memory --initial-memory=65536 --max-memory=65536 --export=start --export=update -target wasm32-freestanding -mcpu generic --listen=-
Build Summary: 0/3 steps succeeded; 1 failed (disable with --summary none)
install transitive failure
└─ install cart transitive failure
   └─ zig build-exe cart ReleaseSmall wasm32-freestanding 1 errors
/usr/lib64/zig/0.11.0/lib/std/start.zig:559:45: error: root struct of file 'main' has no member named 'main'
    switch (@typeInfo(@typeInfo(@TypeOf(root.main)).Fn.return_type.?)) {
                                        ~~~~^~~~~
/usr/lib64/zig/0.11.0/lib/std/start.zig:201:9: note: called from here
    _ = @call(.always_inline, callMain, .{});
        ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```

**Comment by bhansconnect** [comment]
If you use 0.11.0, this version of the template should work: https://github.com/aduros/wasm4/tree/4f840a0cb73b16a57ca348569e48ca2bc91b439f/cli/assets/templates/zig

Not sure why someone upgrade to 0.12.0 which is a moving target with no stability guarantees.

**Comment by mrBen** [comment]
> Not sure why someone upgrade to 0.12.0 which is a moving target with no stability guarantees.

Because that's what Zig recommends? From the [Getting Started](https://ziglang.org/learn/getting-started/):

> Zig releases tend to be far apart and eventually become stale given the current speed of development, […] we encourage you to upgrade to a nightly build.

**Comment by bhansconnect** [comment]
Fair enough, just means regular PRs. But I also get the staleness problem. Just a harder problem for libraries.

This is a good read on a middle ground: https://devlog.hexops.com/2024/announcing-nominated-zig/

**Comment by phcarvalho** [comment]
I was having some problems to build on version 0.13.0 and was able to execute it by changing `.root_source_file` value from `.{ .path = "src/main.zig" }` to `.{ .cwd_relative = "src/main.zig" }`  on the **build.zig** file:

- Before
```zig
    const exe = b.addExecutable(.{
        .name = "cart",
        .root_source_file = .{ .path = "src/main.zig" },
        .target = b.resolveTargetQuery(.{
            .cpu_arch = .wasm32,
            .os_tag = .freestanding,
        }),
        .optimize = b.standardOptimizeOption(.{}),
    });
```

- After
```zig
    const exe = b.addExecutable(.{
        .name = "cart",
        .root_source_file = .{ .cwd_relative = "src/main.zig" },
        .target = b.resolveTargetQuery(.{
            .cpu_arch = .wasm32,
            .os_tag = .freestanding,
        }),
        .optimize = b.standardOptimizeOption(.{}),
    });
```

**Comment by peterhellberg** [comment]
@phcarvalho Note that you should do `.root_source_file = b.path("src/main.zig"),` with current versions of Zig.

_So something along these lines:_
```zig
    const exe = b.addExecutable(.{
        .name = "cart",
        .root_source_file = b.path("src/main.zig"),
        .target = b.resolveTargetQuery(.{
            .cpu_arch = .wasm32,
            .os_tag = .freestanding,
        }),
        .optimize = .ReleaseSmall,
    });
```

**Comment by hidde-vb** [comment]
Reanimating this thread: I think the current template should be updated so it builds on 0.14.x and 0.15.x. This is what most people are using and starting with a broken template is not ideal.

I'll create a small PR.

**Comment by peterhellberg** [comment]
@hidde-vb I would expect people to drop off 0.14.x pretty quickly after 0.16 has been released, hopefully getting pretty close by now.

Myself I'm still using my own tooling ([w4](https://github.com/peterhellberg/w4) and [w4-init](https://github.com/peterhellberg/w4-init)) when using ⚡ [Zig](https://ziglang.org/) for WASM-4 
_(I try to keep my code compatible with `0.16-dev` (and `zig-0.15.2`), something most people might not do as you pointed out)_

> [!Note]
> I just checked and I can build the template under `/cli/assets/templates/zig/` in this repo using both `zig-0.15.2` and `zig-0.16.0-dev` (_3133+5ec8e45f3_)

**Comment by davidhesselbom** [comment]
@peterhellberg I tried following the guide on the website to set up wasm-4 just now, and I get a build.zig that looks like this:

```
    const exe = b.addExecutable(.{
        .name = "cart",
        .root_source_file = b.path("src/main.zig"),
        .target = b.resolveTargetQuery(.{
            .cpu_arch = .wasm32,
            .os_tag = .freestanding,
        }),
        .optimize = b.standardOptimizeOption(.{}),
    });
```

Zig is 0.16.0. To make the template build, I had to modify it into this:

```
    const exe = b.addExecutable(.{
        .name = "cart",
        .root_module = b.createModule(.{
            .root_source_file = b.path("src/main.zig"),
            .target = b.resolveTargetQuery(.{
                .cpu_arch = .wasm32,
                .os_tag = .freestanding,
            }),
            .optimize = b.standardOptimizeOption(.{}),
        }),
    });
```

I used the Windows installer I found here: https://wasm4.org/docs/getting-started/setup?code-lang=zig#no-scroll

`w4 --version` outputs 2.7.1, which appears to be the latest version (December 2024): https://github.com/aduros/wasm4/releases

`/cli/assets/templates/zig/` file had a change similar to the one I made in a commit made over 6 months later, so is not part of the latest release: https://github.com/aduros/wasm4/commit/1d2fc20cbe1fd9d56384c9ab040cb55b959f5d11
